QUESTION_BANK = {
    1: [
        {
            "type": "single_choice",
            "question": "学习画像初始化阶段，系统最应该优先采集哪一类信息来制定个性化学习路径？",
            "options": ["已掌握知识点、薄弱点、目标分数和可用学习时间", "电脑型号和屏幕尺寸", "是否喜欢深色主题", "随机生成的学习编号"],
            "answer": "已掌握知识点、薄弱点、目标分数和可用学习时间",
            "explanation": "学习画像服务于路径规划，关键输入是目标、基础、时间约束和薄弱知识点。",
            "examPoint": "学习状态建模",
            "difficulty": "easy",
            "tags": ["画像", "路径规划"],
        },
        {
            "type": "short_answer",
            "question": "请说明“学习画像”如何影响后续的知识点推荐顺序。",
            "options": [],
            "answer": "学习画像会把目标分数、考试时间、掌握度、错题和学习时长转化为优先级，使薄弱且高权重的知识点优先进入今日路径。",
            "explanation": "画像不是静态标签，而是路径规划、风险评分和资源推荐的共同上下文。",
            "examPoint": "个性化推荐依据",
            "difficulty": "normal",
            "tags": ["画像", "推荐"],
        },
    ],
    2: [
        {
            "type": "single_choice",
            "question": "操作系统的核心职责最准确的是哪一项？",
            "options": ["管理硬件资源并向应用提供抽象接口", "只负责运行浏览器", "替代编译器生成机器码", "只管理网络连接"],
            "answer": "管理硬件资源并向应用提供抽象接口",
            "explanation": "操作系统统一管理 CPU、内存、文件和设备，并通过系统调用向应用程序提供服务。",
            "examPoint": "操作系统定义",
            "difficulty": "easy",
            "tags": ["OS 职责", "系统调用"],
        },
        {
            "type": "multiple_choice",
            "question": "下列哪些属于操作系统提供的典型抽象？",
            "options": ["进程", "虚拟内存", "文件", "高级语言语法树"],
            "answer": ["进程", "虚拟内存", "文件"],
            "explanation": "进程抽象 CPU 执行，虚拟内存抽象地址空间，文件抽象外存数据；语法树主要属于编译原理。",
            "examPoint": "OS 抽象",
            "difficulty": "normal",
            "tags": ["进程", "虚拟内存", "文件"],
        },
        {
            "type": "diagnosis",
            "question": "某同学认为“系统调用就是普通函数调用，只是名字由操作系统提供”。请指出这个说法的关键错误。",
            "options": [],
            "answer": "系统调用会触发从用户态到内核态的受控切换，由内核完成特权操作；普通函数调用不涉及权限级别切换。",
            "explanation": "系统调用的本质是用户程序请求内核服务的边界机制，区别在于特权级、陷入和内核服务。",
            "examPoint": "系统调用与用户态/内核态",
            "difficulty": "normal",
            "tags": ["系统调用", "内核态"],
        },
    ],
    3: [
        {
            "type": "single_choice",
            "question": "进程与线程的主要区别是？",
            "options": ["进程是资源分配单位，线程是 CPU 调度执行单位", "线程拥有独立地址空间", "进程不能并发", "线程之间一定不能共享资源"],
            "answer": "进程是资源分配单位，线程是 CPU 调度执行单位",
            "explanation": "进程通常拥有独立资源和地址空间，线程是进程内的执行流，共享进程资源。",
            "examPoint": "进程线程区别",
            "difficulty": "easy",
            "tags": ["进程", "线程"],
        },
        {
            "type": "scenario",
            "question": "一个 Web 服务器需要同时处理大量客户端请求，但共享同一份缓存。使用多线程模型的主要优势是什么？",
            "options": ["线程切换和共享数据成本较低", "每个线程都有独立磁盘", "线程完全不会产生同步问题", "线程不需要 CPU 调度"],
            "answer": "线程切换和共享数据成本较低",
            "explanation": "同进程内线程共享地址空间，便于共享缓存，但仍需要互斥和同步保护共享数据。",
            "examPoint": "线程模型应用",
            "difficulty": "normal",
            "tags": ["线程", "共享资源"],
        },
        {
            "type": "diagnosis",
            "question": "某同学在 P/V 操作题中总是把互斥信号量和同步信号量混用。请给出判断两类信号量的步骤。",
            "options": [],
            "answer": "先判断是否保护临界区，若是则用互斥信号量且初值通常为 1；若是约束事件先后顺序，则用同步信号量，初值取决于可用资源或先发生条件。",
            "explanation": "互斥解决同一资源不能同时访问，同步解决多个事件之间的顺序或数量约束。",
            "examPoint": "信号量互斥与同步",
            "difficulty": "hard",
            "tags": ["PV 操作", "同步互斥"],
        },
    ],
    4: [
        {
            "type": "calculation",
            "question": "三个作业到达时间均为 0，运行时间分别为 P1=8、P2=4、P3=2。采用非抢占 SJF，平均等待时间是多少？",
            "options": ["2.67", "4", "6", "8"],
            "answer": "2.67",
            "explanation": "SJF 顺序为 P3、P2、P1，等待时间分别为 0、2、6，平均等待时间为 (0+2+6)/3=2.67。",
            "examPoint": "SJF 平均等待时间",
            "difficulty": "hard",
            "tags": ["SJF", "等待时间"],
        },
        {
            "type": "single_choice",
            "question": "时间片轮转 RR 算法中，时间片过小通常会导致什么问题？",
            "options": ["上下文切换开销增大", "所有进程永远阻塞", "平均等待时间一定为 0", "无法实现并发"],
            "answer": "上下文切换开销增大",
            "explanation": "时间片太小会频繁切换上下文，降低 CPU 有效利用率；太大则退化接近 FCFS。",
            "examPoint": "RR 时间片影响",
            "difficulty": "normal",
            "tags": ["RR", "时间片"],
        },
        {
            "type": "multiple_choice",
            "question": "下列哪些调度指标常用于评价 CPU 调度算法？",
            "options": ["平均等待时间", "周转时间", "响应时间", "页表项长度"],
            "answer": ["平均等待时间", "周转时间", "响应时间"],
            "explanation": "页表项长度属于内存管理问题，不是调度算法主要评价指标。",
            "examPoint": "调度评价指标",
            "difficulty": "normal",
            "tags": ["调度", "评价指标"],
        },
    ],
    5: [
        {
            "type": "calculation",
            "question": "某系统页大小为 4KB，逻辑地址为 0x2345。页号和页内偏移分别是多少？",
            "options": ["页号 2，偏移 0x345", "页号 3，偏移 0x245", "页号 0x23，偏移 0x45", "页号 1，偏移 0x1345"],
            "answer": "页号 2，偏移 0x345",
            "explanation": "4KB=0x1000，0x2345 // 0x1000 = 2，页内偏移为 0x345。",
            "examPoint": "分页地址转换",
            "difficulty": "normal",
            "tags": ["分页", "地址转换"],
        },
        {
            "type": "single_choice",
            "question": "TLB 的主要作用是？",
            "options": ["缓存页表项以加速地址转换", "保存文件目录", "替代 CPU 调度", "记录键盘输入"],
            "answer": "缓存页表项以加速地址转换",
            "explanation": "TLB 是页表项快表，命中时可减少访问页表带来的内存访问开销。",
            "examPoint": "TLB",
            "difficulty": "easy",
            "tags": ["TLB", "地址转换"],
        },
        {
            "type": "diagnosis",
            "question": "某同学认为“分段和分页都由程序员手动控制大小，所以没有本质区别”。请指出错误。",
            "options": [],
            "answer": "分页是固定大小的物理管理单位，主要解决离散分配；分段按逻辑模块划分，长度可变，更贴近程序逻辑。",
            "explanation": "分页透明且固定，分段逻辑可见且长度可变，二者解决的问题和地址结构不同。",
            "examPoint": "分页与分段比较",
            "difficulty": "normal",
            "tags": ["分页", "分段"],
        },
    ],
    6: [
        {
            "type": "calculation",
            "question": "页面访问串为 1,2,3,1,4,2,5，物理块数为 3。采用 FIFO 时缺页次数是多少？",
            "options": ["5", "6", "7", "4"],
            "answer": "5",
            "explanation": "依次访问：1缺、2缺、3缺、1命中、4缺淘汰1、2命中、5缺淘汰2，共 5 次。",
            "examPoint": "FIFO 缺页计算",
            "difficulty": "hard",
            "tags": ["FIFO", "缺页次数"],
        },
        {
            "type": "single_choice",
            "question": "LRU 页面置换算法淘汰的是哪一页？",
            "options": ["最近最久未使用的页面", "最早进入内存的页面", "未来最长时间不使用的页面", "编号最大的页面"],
            "answer": "最近最久未使用的页面",
            "explanation": "LRU 根据过去访问历史近似局部性，淘汰最近最长时间没有被访问的页面。",
            "examPoint": "LRU 定义",
            "difficulty": "easy",
            "tags": ["LRU", "页面置换"],
        },
        {
            "type": "multiple_choice",
            "question": "关于 OPT、FIFO、LRU，下列说法正确的是？",
            "options": ["OPT 需要知道未来访问序列", "FIFO 可能出现 Belady 异常", "LRU 是栈算法，通常不出现 Belady 异常", "OPT 总是最容易在真实系统中直接实现"],
            "answer": ["OPT 需要知道未来访问序列", "FIFO 可能出现 Belady 异常", "LRU 是栈算法，通常不出现 Belady 异常"],
            "explanation": "OPT 是理论最优但需要未来信息，真实系统难直接实现；FIFO 可能 Belady 异常；LRU 属于栈类思想。",
            "examPoint": "页面置换算法比较",
            "difficulty": "hard",
            "tags": ["OPT", "FIFO", "LRU", "Belady"],
        },
        {
            "type": "diagnosis",
            "question": "某同学计算 LRU 时，只在缺页时更新页面的最近使用顺序，命中时不更新。这个错误会导致什么后果？",
            "options": [],
            "answer": "会把刚刚命中的页面仍然当作很久未使用，后续可能错误淘汰它，导致缺页次数和置换过程都不正确。",
            "explanation": "LRU 每次访问都要更新最近使用顺序，不论命中还是缺页。",
            "examPoint": "LRU 过程模拟易错点",
            "difficulty": "hard",
            "tags": ["LRU", "错因诊断"],
        },
    ],
    7: [
        {
            "type": "single_choice",
            "question": "inode 主要保存什么？",
            "options": ["文件元数据和数据块索引信息", "CPU 时间片", "页表基址", "进程状态"],
            "answer": "文件元数据和数据块索引信息",
            "explanation": "inode 保存权限、大小、时间戳以及直接/间接块索引等信息。",
            "examPoint": "inode",
            "difficulty": "easy",
            "tags": ["inode", "文件系统"],
        },
        {
            "type": "multiple_choice",
            "question": "下列哪些属于文件分配方式？",
            "options": ["连续分配", "链式分配", "索引分配", "时间片分配"],
            "answer": ["连续分配", "链式分配", "索引分配"],
            "explanation": "时间片分配属于 CPU 调度概念，不是文件物理分配方式。",
            "examPoint": "文件分配方式",
            "difficulty": "normal",
            "tags": ["连续分配", "链式分配", "索引分配"],
        },
        {
            "type": "scenario",
            "question": "如果文件需要频繁随机访问，并且大小可能持续增长，哪种分配方式更合适？",
            "options": ["索引分配", "单纯链式分配", "只使用连续分配", "不分配磁盘块"],
            "answer": "索引分配",
            "explanation": "索引分配通过索引块定位数据块，兼顾随机访问和扩展能力。",
            "examPoint": "文件分配方式选择",
            "difficulty": "normal",
            "tags": ["索引分配", "随机访问"],
        },
    ],
    8: [
        {
            "type": "scenario",
            "question": "期末综合题同时考查进程调度和页面置换时，合理的解题顺序是什么？",
            "options": ["先拆分模块，再分别列状态表或时间线", "直接猜最终答案", "只看题目最后一句", "忽略所有中间过程"],
            "answer": "先拆分模块，再分别列状态表或时间线",
            "explanation": "综合题应先识别模块，再对调度、内存、文件等子问题分别建表推导。",
            "examPoint": "综合题拆解",
            "difficulty": "normal",
            "tags": ["综合题", "解题策略"],
        },
        {
            "type": "short_answer",
            "question": "请给出操作系统综合复习的一个闭环流程。",
            "options": [],
            "answer": "先复述核心概念，再做代表例题，记录错因，针对错因重做同类题，最后用小测验验证是否真正掌握。",
            "explanation": "闭环复习强调概念、例题、错因和再测，不只是被动看答案。",
            "examPoint": "复习闭环",
            "difficulty": "easy",
            "tags": ["复习策略", "错题修复"],
        },
    ],
}


def local_questions(knowledge_point_id: int, count=5):
    base = QUESTION_BANK.get(knowledge_point_id) or QUESTION_BANK[8]
    questions = []
    index = 0
    while len(questions) < count:
        item = base[index % len(base)]
        questions.append({**item, "id": len(questions) + 1, "source": "local-bank"})
        index += 1
    return questions
